# Generated by Django 3.2.8 on 2021-11-04 17:27

from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, validators=[msgserver.models.validate_key, msgserver.models.validate_unique_key]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=160, validators=[msgserver.models.validate_msg_length]),
        ),
    ]
